---
- name: Configurar rede
  hosts: localhost
  connection: local
  become: yes
  tasks:

  - name: Desativar NetworkManager
    ansible.builtin.systemd:
      name: NetworkManager
      enabled: no
  - name: Desativar NetworkManager-wait-online
    ansible.builtin.systemd:
      name: NetworkManager-wait-online
      enabled: no
  - name: Desativar NetworkManager-dispatcher
    ansible.builtin.systemd:
      name: NetworkManager-dispatcher
      enabled: no

  - name: Copiar arquivo de configuração de rede para /etc/systemd/network/
    ansible.builtin.template:
      src: templates/static.network.j2
      dest: /etc/systemd/network/static.network

  - name: Ativar e reiniciar systemd-networkd
    ansible.builtin.systemd:
      name: systemd-networkd
      enabled: yes
      state: restarted